### PR TITLE
Unset RollingRestart flag before comparing CassandraCluster objects in MultiCasskop

### PR DESCRIPTION
**Pull request by cscetbon**
| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | []
| API breaks?     | []
| Deprecations?   | []
| License         | Apache 2.0

MultiCasskop prevents a rolling restart by rollbacking the change when it sees the flag RollingRestart being set

### CODE REVIEW

**Comment by fdehay** [comment]
If I understand correctly, you are unsetting the flag RollingRestart in the spec of the CC.
Will this not prevent the Rolling Restart to occur at CassKop level?
May be you are working on a copy of the actual CC and then it would work. Just want to check :)

**Comment by allamand** [comment]
There are also other fields that are removed for the comparison, I think you just need to add this one also

**Comment by cscetbon** [comment]
> If I understand correctly, you are unsetting the flag RollingRestart in the spec of the CC.
> Will this not prevent the Rolling Restart to occur at CassKop level?
> May be you are working on a copy of the actual CC and then it would work. Just want to check :)

Yeah it's just an object used in the comparison to decide if there is a change to apply or not to underlying cassandracluster objects

**Comment by cscetbon** [comment]
I still see some messages that shouldn't be there 
```
time="2020-09-27T18:18:56Z" level=debug msg="CassandraCluster does not exist, we create it " 
  cluster=cassandra-demo kubernetes=k8s-cluster2 namespace=cluster2
time="2020-09-27T18:18:56Z" level=debug msg="Create CassandraCluster" cluster=cassandra-demo 
  kubernetes=k8s-cluster2 namespace=cluster2
time="2020-09-27T18:18:56Z" level=info msg="Just Update CassandraCluster, returning for now.." 
  cluster=cassandra-demo kubernetes=k8s-cluster2 namespace=cluster2
```

It's the last thing I have to figure out before this PR is ready for review

**Review by fdehay — APPROVED** [review]
Ok for me

**Pull request merged**
