### PR TITLE
[Backup] Do not validate Secret for file protocol

### LINKED ISSUE #378: Backup with file protocol failed if secret is not set
## Bug Report

**What did you do?**
Use file protocol for backup location without setting secret name.

**What did you expect to see?**
As described in instaclustr README file protocol does not require authentication, so backup should be created successfully. 

**What did you see instead? Under which circumstances?**
Backup failed with BackupFailedSecretNotFound

**Environment**
* casskop version: casskop:v2.0.2-release

**Possible Solution**
Check for file protocol type, before validating secret.

### PR DESCRIPTION
**Pull request by AKamyshnikova**
File protocol does not need any authentication, but backup will
fail if secret is not set.
Check protocol type before validating secret.

Fixes #378

| Q               | A
| --------------- | ---
| Bug fix?        | [x]
| New feature?    | []
| API breaks?     | []
| Deprecations?   | []
| Related tickets | fixes #X, partially #Y, mentioned in #Z
| License         | Apache 2.0

### CODE REVIEW

**Comment by fdehay** [comment]
Hello @AKamyshnikova,
Could you please rebase your branch on master please?
We have pushed a small fix today to have integration tests work that we need before accepting PRs
Sorry for this
Thanks!

**Comment by AKamyshnikova** [comment]
@fdehay Hi!
I've rebased change master.

**Comment by cscetbon** [comment]
@fdehay looks good to me. We should test that a regular backup still works as it's not tested here. other than that 👍

**Comment by cscetbon** [comment]
@AKamyshnikova it seems part of this code is already included in the volume mounts PR. Is it because the other PR is branched off of this one ?

**Comment by AKamyshnikova** [comment]
@cscetbon Hi! Yes, I just based it on top of this. I could rebase on master the other one when this is merged.

**Review by cscetbon — APPROVED** [review]

**Pull request merged**
