### PR TITLE
Update pod status to CR after setting podLastOperation to StatusFinalizing

### LINKED ISSUE #370: [BUG] Casskop fails to clean up PVC and refuses to handle user requests after crash and restart
## Bug Report

We find that scaling down a single dc rack (by reducing `nodesPerRacks`) might end up in a dirty state (the pod is deleted but the pvc is still there) if the operator crashes in the middle of a reconcile and restarts. The accidental dirty state will also prevent the operator from handling any future user request.

More concretely, when scaling down the dc rack (statefulset), casskop will do the following:
1. detect there is a decommission task, set the in-memory `CR.podLastOperation.status` (previously `StatusOngoing`) to `StatusFinalizing` (but have not issued `Update` to k8s yet)
2. update statefulset's replica to delete the decommissioned pod
3. update CR at the end of reconcile, which will persist the change to`podLastOperation` (to `StatusFinalizing`)
4. in the next round of reconcile: 
   1. if  `podLastOperation` is `StatusOngoing`, try to get the decommissioned pod. If there is an error, the operator directly returns the error. Otherwise, the operator continues its reconcile.
   2. if  `podLastOperation` is `StatusFinalizing`, try to get the decommissioned pod. If encounter `NotFound` error, delete the PVC and set `podLastOperation.status` to `statusDone`

Say we set `nodesPerRacks` from 2 to 1. The operator will run the above steps. If the operator pod crashes after step 2, the decommissioned pod will be deleted (as the statefulset is resized), but `podLastOperation` is still `StatusOngoing` (since 3 is not executed yet). After the operator pod restarts, it will go to branch 4.i, and since the last pod is already deleted, there will be `NotFound` error when trying to get the last pod. The operator simply ends this round of reconcile by returning with the error and is never able to clean up the PVC or serve further user requests. 

**What did you do?**
Set the `nodesPerRacks` from 2 to 1

**What did you expect to see?**
The pod and the pvc get deleted.

**What did you see instead? Under which circumstances?**
The pod is deleted but the pvc is still there. And any further user operation is refused by the operator.

**Environment**
* casskop version:
f87c8e05c1a2896732fc5f3a174f1eb99e936907 (master branch)

* Kubernetes version information:
1.18.9

* Cassandra version:
3.11

**Possible Solution**
A potential solution is to directly issue `Update` after changing `CR.podLastOperation.status` to `StatusFinalizing` in step 1. So that even if the operator crashes in the middle of reconcile, it should still be able to resize the statefulset and delete the pvc, and move to `StatusDone` eventually.

**Additional context**
We are willing to send a PR to help fix this issue.

### PR DESCRIPTION
**Pull request by srteam2020**
| Q               | A
| --------------- | ---
| Bug fix?        | [YES]
| New feature?    | []
| API breaks?     | []
| Deprecations?   | []
| Related tickets | fixes #370
| License         | Apache 2.0

### What's in this PR?

Immediately update pod status to CR after setting podLastOperation to `StatusFinalizing` to avoid decommissioned pod is deleted but podLastOperation is still `StatusOngoing`. 

### Why?

See #370

### CODE REVIEW

**Comment by srteam2020** [comment]
CI fails due to:
```
INFO: Creating docker container
INFO: Copy goss files into container
INFO: Starting docker container
INFO: Container ID: dc0d38be
INFO: Found goss_wait.yaml, waiting for it to pass before running tests
oci runtime error: exec failed: cannot exec a container that has stopped

OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
intx ThreadPriorityPolicy=42 is outside the allowed range [ 0 ... 1 ]
Improperly specified VM option 'ThreadPriorityPolicy=42'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
ERROR: goss_wait.yaml never passed
INFO: Deleting container
== deleteDgossVolumes
dgoss-bootstrap-vol
dgoss-extralib-vol
dgoss-configmap-vol
dgoss-tools-vol
make: *** [Makefile:434: dgoss-bootstrap] Error 1
```
I am not sure whether it is related to our PR

**Comment by cscetbon** [comment]
@srteam2020 it's an issue I've seen recently. Your changes certainly have nothing to do with this issue.

**Comment by cscetbon** [comment]
@srteam2020 looking at your branch I see you are way behind. Please rebase your changes off of master and the error should disappear.

**Comment by fdehay** [comment]
Hi @srteam2020,
Could you please rebase another time on master?
We pushed a fix today on the integration tests we need before accepting PRs
Sorry for this
Franck

**Comment by srteam2020** [comment]
@cscetbon @fdehay 
I have rebased on master and all the checks have passed. Could you take a look at the PR again?

**Comment by fdehay** [comment]
hello @srteam2020,
Sorry for the delay, we discussed your PR "internally" but I forgot to update.
We are a little bit uncomfortable in forcing the update when it should happen later in the reconciliation process.
But in the other hand a decommission is not something our ops team does often, they are more into creating clusters :)
As I said, we have a very light team on this at this moment so I don't want to introduce potential bugs.
Not saying no, just explaining our position and our silence.
Haw critical is it for you? I understand you can reproduce the problem with a tool of yours?

**Comment by fdehay** [comment]
I forgot to say thanks for the rebase and the successfull tests :)

**Comment by cscetbon** [comment]
@fdehay do we move forward on this PR ?

**Review by cscetbon — APPROVED** [review]

**Pull request merged**
